Add tokio codec
bluerobotics/ping-rs pull request #18
Opened 2024-04-09 12:45 UTC by RaulTrombin

This fully implement codec structure using tokio_util Decoder/Encoder.

Add codec and error modules to src.

Codec have it's own tests.

There is an example/test using it with tokio runtime:
`cargo test --features local_runner 
`

Also fails with any panic as the one related in this [issue](https://github.com/bluerobotics/ping-rs/issues/16) for msg_id=1300.

2024-04-09 20:42 UTC, patrickelectric requested changes

2024-04-09 20:42 UTC, patrickelectric commented on src/codec.rs
> +    }
Please also add a text to check a wrong buffer fails.

2024-04-09 20:42 UTC, patrickelectric commented on tests/async_codec.rs
> +            sleep(Duration::from_millis(200)).await;
Can we just remove this sleep ?

2024-04-09 20:42 UTC, patrickelectric commented on tests/async_codec.rs
> +#[cfg_attr(not(feature = "local_runner"), ignore)]
Can we move this to run_ping_test ?

2024-04-09 20:42 UTC, patrickelectric commented on tests/async_codec.rs
> +            Ok(Messages::Ping1D(ping1d::Messages::DeviceId(answer))) => {
We should print all messages.

2024-04-09 20:42 UTC, patrickelectric commented on tests/async_codec.rs
> +                eprintln!("Error on decoder: {:?}", e)
We should panic here

2024-04-10 17:34 UTC, RaulTrombin commented on src/codec.rs
> +    }
ok

2024-04-10 17:35 UTC, RaulTrombin commented on tests/async_codec.rs
> +            sleep(Duration::from_millis(200)).await;
removed both sleeps, tests still fine. Ok

2024-04-10 18:09 UTC, RaulTrombin commented on tests/async_codec.rs
> +#[cfg_attr(not(feature = "local_runner"), ignore)]
different test runtime, also would require pass all dev-dependencies to source, to early, would like to do this after devices.

2024-04-10 18:10 UTC, RaulTrombin commented on tests/async_codec.rs
> +            Ok(Messages::Ping1D(ping1d::Messages::DeviceId(answer))) => {
ok, fill the match arms for each get method request

2024-04-10 18:10 UTC, RaulTrombin commented on tests/async_codec.rs
> +                eprintln!("Error on decoder: {:?}", e)
thks

2024-04-10 18:17 UTC, RaulTrombin commented on tests/async_codec.rs
> +                eprintln!("Error on decoder: {:?}", e)
panic for both cases: "Unexpected package" and "Error on decoder"

2024-04-10 20:22 UTC, joaoantoniocardoso commented on tests/async_codec.rs
> +            assert!(false, "Test failed: {:?}", e);
```suggestion
            panic!("Test failed: {:?}", e);

```

2024-04-10 20:22 UTC, joaoantoniocardoso commented on tests/async_codec.rs
> +                panic!("Unexpected package")
maybe:
```suggestion
                panic!("Unexpected package. {:#?}", &item)
```

2024-04-10 20:22 UTC, joaoantoniocardoso commented on tests/async_codec.rs
> +            }
shouldn't we panic here?

2024-04-10 20:22 UTC, joaoantoniocardoso commented on tests/async_codec.rs
> +        );
can't we use an assert to do this check instead of a println?

2024-04-10 20:22 UTC, joaoantoniocardoso commented on src/codec.rs
> +            };
maybe:
```suggestion
            let Some(byte) = src.get(consumed) else {
                return Ok(None);
            };
```

2024-04-10 20:22 UTC, joaoantoniocardoso commented on src/codec.rs
> +                }
just checking... The first match variant modifies consumed, but the next two, don't. Is this the intent?

2024-04-10 23:26 UTC, RaulTrombin commented on src/codec.rs
> +                }
Yeah, yeah will just advance with (consumed+1(actual_byte)).
and in a specif case, when somehow receive a half package, it will advance with consumed and in next loop will check if a byte is available.

2024-04-10 23:38 UTC, RaulTrombin commented on tests/async_codec.rs
> +        );
assert!(item.has_valid_crc());

2024-04-10 23:40 UTC, RaulTrombin commented on tests/async_codec.rs
> +            }
we should, thks

2024-04-10 23:44 UTC, RaulTrombin commented on src/codec.rs
> +            };
thks

2024-04-11 01:05 UTC, joaoantoniocardoso commented on tests/async_codec.rs
> +            }
I think this match-then-panic is pretty much equivalent to a simple unwrap or expect.

2024-04-11 16:21 UTC, joaoantoniocardoso commented on tests/async_codec.rs
> +    }
same panic pattern here.

2024-04-11 18:13 UTC, joaoantoniocardoso approved these changes

2024-04-11 18:40 UTC, patrickelectric commented on src/codec.rs
> +#[cfg(test)]
This should be squashed with e841a96ab22e8541ded1495f4610ccef9a8c08b4

2024-04-11 18:40 UTC, patrickelectric commented on tests/async_codec.rs
> +            Ok(Messages::Ping1D(ping1d::Messages::DeviceId(answer))) => {
Needs https://github.com/bluerobotics/ping-rs/pull/21

2024-04-11 18:41 UTC, patrickelectric requested changes

2024-04-11 18:41 UTC, patrickelectric commented on tests/async_codec.rs
> +                println!("{:?}", answer)
```suggestion
                println!("{answer:?}")
```

2024-04-11 18:57 UTC, patrickelectric approved these changes

2024-04-11 18:57 UTC, merged