Add device module and example [WIP]
bluerobotics/ping-rs pull request #23
Opened 2024-04-18 17:17 UTC by RaulTrombin

2024-04-24 18:06 UTC, joaoantoniocardoso commented on src/device.rs
> +    }
This task is likely to leave forever, as the only way out of the loop is if the broadcast_tx fails to send (by being closed), but who closes it?

2024-04-25 12:00 UTC, patrickelectric commented on src/device.rs
> +                            || common::NackStruct::id() == answer.message_id)
`common::AckStruct::id() != answer.message_id && common::NackStruct::id() != answer.message_id`

2024-04-25 12:02 UTC, patrickelectric commented on src/device.rs
> +                                return Err(PingError::NackError(answer));
The answer here is unnecessary, there is not useful inside

2024-04-25 12:02 UTC, patrickelectric commented on src/device.rs
> +                            _ => return Err(PingError::TryFromError(answer)), // Almost unreachable, but raises error ProtocolMessage
Shoudnt this be a continue ?

2024-04-25 12:04 UTC, patrickelectric commented on src/device.rs
> +            Ok(_result) => Ok(()),
This should return the future result, not an empty ok

2024-04-25 12:09 UTC, patrickelectric commented on src/device.rs
> +                            dbg! {_e};
This should use parentheses not braces

2024-04-25 12:10 UTC, patrickelectric commented on src/device.rs
> +        'serial_stream: loop {
It's better to call it as outside_loop or something that make it more explicit that we are talking about a loop that encapsulates the main logic, over "serial_stream", that's pretty generic what it does.

2024-04-25 12:31 UTC, patrickelectric commented on examples/ping_1d.rs
> +    println! ("Creating a subscription channel which will receive 30 Profile measurements, we'll check this after the next methods!");
This is probabaly missing cargo fmt

2024-04-25 13:33 UTC, RaulTrombin commented on examples/ping_1d.rs
> +mod cli_args {
k, please check the newer version

2024-04-25 13:36 UTC, RaulTrombin commented on examples/ping_1d.rs
> +    port.set_exclusive(false)?;
I believe it's to allow reuse the ports in the same scope,
https://docs.rs/tokio-serial/latest/tokio_serial/struct.SerialStream.html#method.set_exclusive

It was into example tokio_serial, still works without it, let remove and keep it to future if it's required

2024-04-25 13:41 UTC, RaulTrombin commented on src/device.rs
> +                                return Err(PingError::NackError(answer));
For logging it could be usefull, since it have the request id inside it

2024-04-25 14:08 UTC, RaulTrombin commented on src/device.rs
> +    }
Is there a master "panic!" for this case?
I believe if it get some faltal error on serial bus it should stop.
We can create a manager which retry stabilish the port, but I not but the port creation inside the device yet.

2024-04-25 14:22 UTC, RaulTrombin commented on src/device.rs
> +                            dbg! {_e};
changed to tracing, since we merged last related PR

2024-04-25 18:22 UTC, patrickelectric requested changes

2024-04-25 18:22 UTC, patrickelectric commented on src/device.rs
> +                                return Ok(answer);
In this case, we should return an empty Ok since ack will always contain message_id
https://docs.bluerobotics.com/ping-protocol/pingmessage-common/#1-ack

2024-04-25 18:22 UTC, patrickelectric commented on src/device.rs
> +                                return Err(PingError::NackError(answer));
Since Nack contains the error contains nack_message https://docs.bluerobotics.com/ping-protocol/pingmessage-common/#2-nack it's better to return the message itself or the struct. 
`Err(PingError::NackError(String))`

2024-04-25 19:03 UTC, RaulTrombin commented
@patrickelectric with you

2024-04-25 19:13 UTC, patrickelectric approved these changes

2024-04-25 19:13 UTC, merged