Add: Automatic function generation, for get,set and control [WIP]
bluerobotics/ping-rs pull request #31
Opened 2024-05-02 15:17 UTC by RaulTrombin

2024-05-02 18:34 UTC, patrickelectric requested changes

2024-05-02 18:34 UTC, patrickelectric commented on build/parser.rs
> +            quote::format_ident!("get_{}", self.name.to_case(Case::Snake))
Functions should follow the pattern of: `device_id()`, `set_device_id()`.
There is no need to use `get_` prefix, this follows as well our other ping apis.

2024-05-02 18:34 UTC, patrickelectric commented on build/parser.rs
> +        }
Please fix the indentation.

2024-05-02 18:34 UTC, patrickelectric commented on build/parser.rs
> +                let data_type = vector.data_type.to_rust();
Why is this necessary ?

2024-05-02 18:34 UTC, patrickelectric commented on build/parser.rs
> +    category: String,
This should use enums.

2024-05-02 18:34 UTC, patrickelectric commented on build/parser.rs
> +        pub fn new(port: tokio_serial::SerialStream) -> Self {
We should not use serial, but an abstraction over io. This should work with serial, tcp, udp and file.

2024-05-02 18:34 UTC, patrickelectric commented on examples/ping_1d.rs
> +    ) = tokio::try_join!(res1, res2, res3, res4, res5, res6).expect("Failed to join results");
```rs
let (
    protocol_version_struct,
    device_id_struct,
    gain_setting_struct,
    processor_temperature_struct,
    voltage5_struct,
    speed_of_sound_struct,
) = tokio::try_join!(
    ping1d.get_protocol_version(),
    ping1d.get_device_id(),
    ping1d.get_gain_setting(),
    ping1d.get_processor_temperature(),
    ping1d.get_voltage_5(),
    ping1d.get_speed_of_sound()
).expect("Failed to join results");
``

2024-05-07 14:46 UTC, RaulTrombin commented on build/parser.rs
> +        pub fn new(port: tokio_serial::SerialStream) -> Self {
Please check proposal

2024-05-07 15:02 UTC, RaulTrombin commented
@patrickelectric @joaoantoniocardoso 
Please check updated PR,
created new emit_fn(), enum category, io abstraction and fully implemented set/get/setting with their descriptions.

2024-05-07 20:41 UTC, RaulTrombin commented
@patrickelectric 
Fully functional through udp stream from BlueOS ( to be implemented on a next PR updating example and clap fields)
![image](https://github.com/bluerobotics/ping-rs/assets/80598030/2f84f1b3-a8b2-45a6-8297-cf70f2b7c263)

2024-05-07 20:54 UTC, patrickelectric approved these changes

2024-05-07 20:54 UTC, merged