Update: Docs for release
bluerobotics/ping-rs pull request #36
Opened 2024-05-14 23:13 UTC by RaulTrombin

Please check:
https://github.com/RaulTrombin/ping-rs/tree/Update_docs

2024-05-15 11:03 UTC, ES-Alexander requested changes
Some suggested content changes :-)

The main fundamental difference is emphasising that the library implements a protocol for device types, not specific devices - i.e. there can be multiple different devices that fit within / make use of the message set for a particular device type (e.g. Ping and Ping2 are both `Ping1D` type devices).

2024-05-15 13:18 UTC, RaulTrombin commented
> Some suggested content changes :-)
> 
> The main fundamental difference is emphasising that the library implements a protocol for device types, not specific devices - i.e. there can be multiple different devices that fit within / make use of the message set for a particular device type (e.g. Ping and Ping2 are both `Ping1D` type devices).

Thks @ES-Alexander, I really appreciate the suggestions. Now it's easier to navigate the documentation and their related devices.

2024-05-15 13:36 UTC, patrickelectric commented on README.md
> +[SONARs](https://en.wikipedia.org/wiki/Sonar), or **So**und **N**avigation **A**nd **R**anging devices, transmit sound waves and measure their reflections to detect surrounding obstacles and objects.
That would probably be [SoNARs]

2024-05-15 13:47 UTC, RaulTrombin commented on README.md
> +[SONARs](https://en.wikipedia.org/wiki/Sonar), or **So**und **N**avigation **A**nd **R**anging devices, transmit sound waves and measure their reflections to detect surrounding obstacles and objects.
https://bluerobotics.com/learn/understanding-and-using-scanning-sonars/#operating-principles
What about replace `or`
SONARs, `from` Sound...

2024-05-15 14:30 UTC, patrickelectric commented on README.md
> +[SONARs](https://en.wikipedia.org/wiki/Sonar), or **So**und **N**avigation **A**nd **R**anging devices, transmit sound waves and measure their reflections to detect surrounding obstacles and objects.
Usually only the first letter is capitalized. But no hard feelings. Once @ES-Alexander approves it we can merge.

2024-05-16 01:49 UTC, ES-Alexander approved these changes

2024-05-16 13:16 UTC, patrickelectric approved these changes

2024-05-16 13:16 UTC, merged